<script>
const arr = ["shoes","pant" ,"kurta"];

const promise = createOrder(cart);
console.log(promise) //  Promise {<pending>}
//when we pass down the chain we need to return from chain
// if there is error in any part of chain then it will go to catch block
promise
    .then((function(orderId) { //resolve promise
        console.log(orderId); // 1234 after 5 sec
        return orderId;
    })
    .then((function(orderId) { //resolve promise
       return  proceedToPayment(orderId)
    })
    .then((function(paymentInfo) { //resolve promise
       console.log(paymentInfo)
        return paymentInfo;
    })
    .catch((error) => { //reject promise
       console.log(error.message);
    });

//  It will only check error at top of it and if it is not handled then it will go to catch block
promise
    .then((function(orderId) { //resolve promise
        console.log(orderId); // 1234 after 5 sec
        return orderId;
    }).catch((error) => { //reject promise
            console.log(error.message);
        })
        .then((function(orderId) { //resolve promise
            return  proceedToPayment(orderId)
        })
            .then((function(paymentInfo) { //resolve promise
                console.log(paymentInfo)
                return paymentInfo;
            });

promise
    .then((function(orderId) { //resolve promise
        console.log(orderId); // 1234 after 5 sec
        return orderId;
    }).then((function(orderId) { //resolve promise
            return  proceedToPayment(orderId)
        }).then((function(paymentInfo) { //resolve promise
                console.log(paymentInfo)
                return paymentInfo;
            }).catch((error) => { //reject promise
                console.log(error.message);
            }) .then((function() { //resolve promise
                console.log('No Matter What Happen I Will definietely call')
            })




function createOrder(cart) {
    return new Promise((resolve,reject) => {
        //api call
        if(!validate(cart)){
          const error = new Error('cart is not valid');
          reject(error);

      } else {
          let orderId = 1234;
          if(orderId){
              setTimeout(() => {
                  resolve(orderId);
              },5000);
              // resolve(orderId);
          }
        }

    })
}

function proceedToPayment(orderId) {
    return new Promise((resolve,reject) => {
        //api call
        let paymentInfo = {
            paymentId: 1234,
            amount: 5000,
            orderId
        }
        if(paymentInfo){
                resolve(paymentInfo);
        } else {
            const error = new Error('payment failed');
            reject(error);
        }
    })
}

function validate(cart) {
    if(cart.length > 0) {
        return true;
    } else {
        return false;
    }
}

</script>